#!/usr/bin/env python2
import re
from sys import argv

flexlog_file     = '/home/chris/.flexget/flexget.log'
downloaded_array = []

for line in open(flexlog_file):
  if "download" and not "ERROR" in line:
    downloaded_array.append(line)

for download in downloaded_array:
  show_match = re.match(r'(\d{4}-\d{2}-\d{2} \d{2}:\d{2}).*Downloading: (\w.*?) - ([sS]\d.[eE]\d.).*', download)
  if show_match:
    show_season = "\033[33m%s \033[35m%s" % (show_match.group(2), show_match.group(3))
    print "%s\033[0m on \033[31m%s" % (show_season.rjust(50), show_match.group(1))

